### ISSUE TITLE
Hello Can u tell me how to turn these xml to nxgz format and how to build a fake update server

### ISSUE THREAD

**Issue by wowzql** [Tachiorz/MS2-English-Translation#47]
Hello~~ Can u help me? I want to make translate maplestory2 to chinese. Lots chinese player want play this game,But cant read Korean,I can read it and I have much time. So I think I can do it. But I cant unpack and pack the game file. Can u teach or help me ? Thank u ~My email ：Wish your reply.

**Comment by Sunaries** [comment]
As far as I know, the creator is not going to release any methods on how to do this.

**Comment by wowzql** [comment]
I am very sincere.If OK I can pay money to learn it. Can u help me ? Wish your reply~~

**Comment by Tachiorz** [comment]
Sorry, but I don't want to disclose packaging algorithms, because it will eventually lead to cheating (like in tree of savior for example).
I can make packages with your translation, but I don't guaranty stable releases, won't do it often and only until official release in China.
Maintaining patch server for translation is on your shoulders. It should run nginx, I'll provide configuration for it (I won't provide support on linux server administration, you should know how to run it).
Just fork this repository and provide me a link, I'll upload ready packages somewhere

**Comment by Smallthing** [comment]
ok I'll do this ,thank you

**Comment by wowzql** [comment]
OK , and can u tell me ur email ? My email is wowzql@gmail.com. And i can sent my linux server information to u now by email . Can u help  me to configuration for it?

**Comment by wowzql** [comment]
And I have some questions. Because MS2 is korean game. I'm not sure Chinese character can be shown in  game. It maybe need change font style.

**Comment by jh961202** [comment]
I guess MS2 uses UTF-8, so there won't be problem for displaying Chinese.

**Comment by wowzql** [comment]
I dont think so. If font style not fit, it will display black box.

**Comment by Tachiorz** [comment]
Game have CN font already, see fontconfig.txt. If it won't work out of the box - I'll mod this file and fix files.nfo2 accordingly

**Comment by wowzql** [comment]
Thank u , I and my friend translate Korean to Chinese since received ur message ~  
Can u email me and we use email to chat? My email is wowzql@gmail.com  ~
