### ISSUE TITLE
Are this project and the server not maintained anymore?

### ISSUE THREAD

**Issue by alphalzh** [Tachiorz/MS2-English-Translation#57]
Hi Tachiorz, 

Thanks a lot for your hard work on this project.
Find this tool from reddit, really excited to try it but it isn't working any more. 
Just want to know if you are still working on this/maintaining the server, since this could mean a lot for me & other players. On reddit there's a bunch of people waiting for a workable solution.

Best Regards,
Greg

**Comment by Tachiorz** [comment]
It's maintained. The repo just become private because some user data mained
it and spred rumors on unreleased content. It should work unless some patch
broke it. I'm not actively playing right now. Manual on reddit a bit
incorrect. You souldnt replace any files in the client.
Anyway, I'll test it when I have time
On Apr 12, 2016 09:30, "alphalzh" notifications@github.com wrote:

Hi Tachiorz,

Thanks a lot for your hard work on this project.
Find this tool from reddit, really excited to try it but it isn't working
any more.
Just want to know if you are still working on this/maintaining the server,
since this could mean a lot for me & other players. On reddit there's a
bunch of people waiting for a workable solution.

Best Regards,
Greg

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/Tachiorz/MS2-English-Translation/issues/57

**Comment by alphalzh** [comment]
Thanks for your reply!
I'm raising this issue since I tried to alter the /etc/hosts file as instructed and then the game launcher stuck at 27%. Happy to hear that you may test it though.
